### ISSUE TITLE
Lag when windows are minimized but not when appearing

### ISSUE THREAD

**Issue by wiktorwiktor12** [ALTaleX531/OpenGlass#1]
https://www.youtube.com/watch?v=ZcGJptMYSmM
video showcasing the issue

for some reason, when everything is minimized, any window that isnt minimized will lag, but there will be no lag if everything is not minimized

![image](https://github.com/ALTaleX531/OpenGlass/assets/68821018/03e77ffe-f6ae-42e3-856f-f85f67e742e2)
my settings

**Comment by ALTaleX531** [comment]
Weird.
Are you able to reproduce the bug consistently after a reboot? At the moment, I can't reproduce it on all my machines.

**Comment by wiktorwiktor12** [comment]
yes the bug happens after reboots

**Comment by wiktorwiktor12** [comment]
yes the bug happens after reboots.

**Comment by wiktorwiktor12** [comment]
yes the bug happens after reboots

**Comment by ALTaleX531** [comment]
I'm not sure if the latest version has solved your problem, but I can't reproduce it in any way. Your issue will be treated as low priority, and if anyone has a way to reproduce it consistently, I'll look into what's going on again.

**Comment by wiktorwiktor12** [comment]
doesn't occur as of latest version
