### ISSUE TITLE
add more support for thick borders

### ISSUE THREAD

**Issue by catneptune** [ALTaleX531/OpenGlass#10]
![image](https://github.com/ALTaleX531/OpenGlass/assets/144282272/98b092a5-70cd-4365-9801-bdfa0f023aea)
at first i thought this was out of scope for the project, but interestingly, this has different results, so this could be related to how it is in the code?
![image](https://github.com/ALTaleX531/OpenGlass/assets/144282272/baf8f100-2acf-4121-85d3-2c430663c201)
this is what it looks like in dwmbg, you can see that the top part of the top border is cut off, while in openglass, it is reversed, and the rounded-ness of the bottom left corner is different, could this be an issue with the shader itself and how the code is?

yes, i am using the legacy version for this, i'll check the master branch later

**Comment by ALTaleX531** [comment]
I don't know what adding more support for thick borders actually is. According to my tests, both the dcomp implementation and the legacy implementation have complete support for the [thick border mod](https://github.com/Maplespe/DWMBlurGlass/issues/147#issuecomment-2052520952), though I've never thought of adding support for it on purpose.
![image](https://github.com/ALTaleX531/OpenGlass/assets/105535231/048e96f9-dba2-4493-8408-22b94aa974f7)
The biggest difference between openglass and dwmbg at the moment is that dwmbg calculates the rendering area itself, while openglass uses the rendering area provided by udwm.

**Comment by catneptune** [comment]
> I don't know what adding more support for thick borders actually is. According to my tests, both the dcomp implementation and the legacy implementation have complete support for the [thick border mod](https://github.com/Maplespe/DWMBlurGlass/issues/147#issuecomment-2052520952), though I've never thought of adding support for it on purpose. ![image](https://private-user-images.githubusercontent.com/105535231/346112387-048e96f9-dba2-4493-8408-22b94aa974f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTA0MDksIm5iZiI6MTcyMDE5MDEwOSwicGF0aCI6Ii8xMDU1MzUyMzEvMzQ2MTEyMzg3LTA0OGU5NmY5LWRiYTItNDQ5My04NDA4LTIyYjk0YWE5NzRmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNDM1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjMxYzE3ZjYxYzY0NDZiNjQ2NzJmZjIzZGFiYzFiOTljMWUwZDBkMDIyZDIxNzJhOGQzZmYxZDk3ODE1NTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2zFARSH9a3d3xqPBjIqrzDj_7dEO0ctju0iLY1EHHm8) The biggest difference between openglass and dwmbg at the moment is that dwmbg calculates the rendering area itself, while openglass uses the rendering area provided by udwm.

hm.. that's quite odd, but the glass doesn't expand right for me, im not sure if it happens to you, but you can try by opening mspaint and painting different colors, as in the original post, some areas of the window just don't get anything
![image](https://github.com/ALTaleX531/OpenGlass/assets/144282272/c77f1003-18e7-4f40-b684-be7be3155c50)
i wonder what's causing this.. i guess it could be udwm? i'm not too sure
