### ISSUE TITLE
Weird flickering happening if a window is on top of VMWare on OpenGlass legacy

### ISSUE THREAD

**Issue by ImSwordQueen** [ALTaleX531/OpenGlass#13]
https://github.com/user-attachments/assets/cb8c2e3c-5d49-40cb-83df-13cace67d9a6

**Comment by ALTaleX531** [comment]
It looks like it doesn't get the backdrop rendered using dx very well, I'll look into it later.

**Comment by callumboynton** [comment]
Hi, I think this issue may be relevant to overlapping, I've seen it happen with Wallpaper Engine as well as Discord. See attached video.

https://github.com/user-attachments/assets/e5c03218-43d4-4df5-999c-d8d75c7d0600

**Comment by Dulappy** [comment]
Adding to this, YouTube videos also appear completely black under the glass.
![image](https://github.com/user-attachments/assets/db88ece2-021c-4134-9e2b-deb4ac6bc38f)
What's interesting is that this also occurs with other videos, but not when the content is scrolled far enough down:
Scrolled down:
![image](https://github.com/user-attachments/assets/916506cb-231b-4854-8b62-98c49e234d9d)
Higher on the page:
![image](https://github.com/user-attachments/assets/0dda9709-6ee3-4225-ad34-1d76cfc114fd)

**Comment by ALTaleX531** [comment]
@Dulappy 
I think I probably know why, video playback or some other software that uses dx rendering triggers something like `Direct Flip` or `Independent Flip`, which bypasses DWM and renders directly from the GPU to the display, and I'm not sure what I can do about it. This similar problem also happened to glass8, for example placing the file explorer window on top of Moves & TV, a UWP window, the overlapping part would be rendered as completely transparent.

**Comment by ALTaleX531** [comment]
Moved to #30.
