### ISSUE TITLE
[Legacy branch] Blur breaks on non-Landscape and flipped monitors

### ISSUE THREAD

**Issue by Mrk20200** [ALTaleX531/OpenGlass#15]
### Problem
When a monitor is rotated to anything except Landscape (not flipped) in the display settings, the blur doesn't fully cover the titlebars and dragging other windows over the blur causes visual glitches. When using screen capture tools to take a screenshot of the window, it shows visual artifacts from the edge of the monitor it was dragged from. The blur also seems to not follow the monitor's rotation.

### System Info
(not sure if this info matters)
OS: Windows 10 22H2 (19045.4651)
Tested on OpenGlass Legacy v1.1 and the latest legacy branch compiled from source (in release configuration)

I am unable to test this in a virtual machine because it doesn't allow me to rotate the monitors in the display settings.

### Screenshots
(background is a black and white checkerboard pattern with each cell being 2x2 in size)
From phone camera (different from using screen-capture software):
![phone](https://github.com/user-attachments/assets/b732121e-3750-46a2-9d9c-441c83cfde71)
From using print screen key:
![printscreen](https://github.com/user-attachments/assets/27041665-b9d2-48e1-a91f-4a3bb7c8ca1b)
(the shortcut the above image shows in the blur is from the monitor next to it, and isn't from that monitor)

**Comment by ALTaleX531** [comment]
Oh, I didn't even notice the multi-monitor thing before, I'll check this out.

**Comment by jackhric** [comment]
Having this same issue. Thanks for looking into it!

**Comment by ALTaleX531** [comment]
Fixed.
