### ISSUE TITLE
Blur doesn't extend to border (even after putting the required regedit)

### ISSUE THREAD

**Issue by AryaTwirl** [ALTaleX531/OpenGlass#17]
Hi, as the title says, I notice that the border is not blured.

![Screenshot 2024-07-20 at 23 03 37](https://github.com/user-attachments/assets/fa03304b-5bb7-4b9b-bce5-d16c2e5fe113)

Is there anything I can do? And perhaps the registry is not fully inserted? (I only inserted it in HKCU address)

**Comment by ALTaleX531** [comment]
Look carefully, the blur has already extended to the border.
