### ISSUE TITLE
Composited text

### ISSUE THREAD

**Issue by Undisputed00x** [ALTaleX531/OpenGlass#2]
Is there a way to enable composited text globally, the issue for me is that text color gets transparent on white background. 
[ExplorerBlurMica](https://github.com/Maplespe/ExplorerBlurMica) enabled that but only for the explorer.
<details><summary>Example</summary>
<p>

![Screenshot_2024-05-10_034903](https://github.com/ALTaleX531/OpenGlass/assets/80290008/bb6f14ee-797b-40fe-bf21-fd7cf302417b)

</p>
</details> 

Is there any other way change the transparency of text besides dwm text composition ? I know there is a project [MacType](https://github.com/snowie2000/mactype) but its unstable and doesnt work good for my case.

**Comment by ALTaleX531** [comment]
You seem to misunderstand something, none of these texts on the image are rendered by dwm, and all of these composited texts are rendered by GDI instead. There's no alternative to MacType at the moment, and the request is not related to this project at all. OpenGlass can only control title bar text rendering in Windows 10.

**Comment by Undisputed00x** [comment]
@ALTaleX531 Ty for the info!
