### ISSUE TITLE
Wallpaper Engine compatibility 

### ISSUE THREAD

**Issue by TheDolphinSlayer** [ALTaleX531/OpenGlass#20]
I tried setting various different options, but OpenGlass doesn't render the background of my animated wallpaper/sometimes doesn't render a youtube video leaving a black box.
![image](https://github.com/user-attachments/assets/59b13f35-4d69-44b4-bc3f-7005b5995ca6)
![image](https://github.com/user-attachments/assets/b1e7d39a-05d6-4757-af56-05e09754a231)
But renders other things like the github (green submitnew issue button)

**Comment by ALTaleX531** [comment]
![image](https://github.com/user-attachments/assets/6e2d1793-96db-49ce-851d-3a37073313a8)
Probably has something to do with your hardware, the fix won't come that fast, you can use the master branch first if you want.

**Comment by TorutheRedFox** [comment]
same issue happens with discord when the window is getting repainted

if it remains static it's fine

**Comment by ALTaleX531** [comment]
Moved to #30.
