### ISSUE TITLE
[dcomp branch] 24H2 support?

### ISSUE THREAD

**Issue by teknixstuff** [ALTaleX531/OpenGlass#24]
Just wondering if 24H2 might be supported soon.

**Comment by ALTaleX531** [comment]
Support is not considered until 24H2 appears in [windows11-release-information](https://learn.microsoft.com/en-us/windows/release-health/windows11-release-information).

**Comment by RibShark** [comment]
It has been added.
![image](https://github.com/user-attachments/assets/8be57c20-73a0-4f30-91f7-bfb3a63001a3)
