### ISSUE TITLE
OpenGlass cant get the symbol files for me :(

### ISSUE THREAD

**Issue by mc034** [ALTaleX531/OpenGlass#26]
Even i installed it correctly (not in the user path) it still showes me a Error at startup.("OpenGlass could not download appropriate symbol files") And yes i do have a stable internet connection 👍

**Comment by illusion0001** [comment]
Open x64dbg and download the symbol file manually
![image](https://github.com/user-attachments/assets/254c42b5-972e-4fc3-ba63-1559fe06bee9)

**Comment by morrysillusion** [comment]
hi, im also having this issue with symbol files not downloading. can you give more specific directions on using x64dbg? file do i open in that program to find udwm.dll?

**Comment by illusion0001** [comment]
It's in system32 along with dwmcore. Just right click in symbol tab and find the relevant modules and download symbol for this module. Then copy the symbol to your OpenGlass folder and it will be picked up after pressing retry.

**Comment by morrysillusion** [comment]
ive got the symbols in the folders with open glass, but upon restarting and running it (or completely uninstalling and reinstalling) just doesnt do anything-- i see a window pop up and close immediately, and nothing else changes or shows up afterward.

**Comment by LoveJessyChen** [comment]
My ARM64 Win can't get symbol files.

**Comment by ALTaleX531** [comment]
You can use PDB Downloader or other tools to manually download the symbol files and place them in the `symbols` folder, btw ARM architecture is not supported.

**Comment by ALTaleX531** [comment]
Not responding. Closed.

**Comment by duckydee** [comment]
![image](https://github.com/user-attachments/assets/46e8103c-fc2d-4ec2-a067-a7bc5443902d)
I keep getting the same issue. I've tried on one install of windows that was up to date, and now I'm on a new install that has no updates applied to it. I get this error every time the computer boots. Yes, I do have internet connected. 

> You can use PDB Downloader or other tools to manually download the symbol files and place them in the `symbols` folder, btw ARM architecture is not supported.

PDB downloader appears to download a file, opens an explorer window of the folder it downloaded to, and there's nothing in the folder. 

> It's in system32 along with dwmcore. Open the module in x64dbg, click on symbol tab and find the relevant modules, right click to download symbol for this module. Then copy the symbol folder from your x64dbg folder to your OpenGlass folder and it will be picked up after pressing retry.

Opening uDWM.dll in x64dbg allows me to download symbols, but it looks different than the screenshot illusion0001 posted, and even after putting the files in the openglass folder and clicking retry, nothing changes. Any help would be much appreciated!

**Comment by MagicAndre1981** [comment]
> Not responding. 

this happens because of the Windows firewall , I had to disable it while trying to download the symbols because I don't know which exe I had to whitelist.
