### ISSUE TITLE
Please make Windows Server 2022 compatible with OpenGlass!

### ISSUE THREAD

**Issue by ucm211** [ALTaleX531/OpenGlass#27]
![無題](https://github.com/user-attachments/assets/8cacc706-3fa9-40bd-bb56-29c2d871e062)
![無題2](https://github.com/user-attachments/assets/c2d23f0a-855c-4f51-8bdc-597b120a2a84)
![無題3](https://github.com/user-attachments/assets/c57ac48b-2ea6-4b9c-bf2d-08a275f9ebbd)

**Comment by ALTaleX531** [comment]
You should not use OpenGlass on Windows Server.
