### ISSUE TITLE
Alt Tabbing into a window causes black borders

### ISSUE THREAD

**Issue by uncognic** [ALTaleX531/OpenGlass#28]
When alt tabbing into a window that was minimized, the borders are black for a split second before becoming aero. The same happens with the start menu except only the aero parts are black. Startisback. Windows 10 LTSC 19044.4780, and using the latest version of ImSwordQueens transformation pack.

**Comment by uncognic** [comment]
![image](https://github.com/user-attachments/assets/2f4c7114-e1fe-4621-a1f1-c9fbadd7aab0)
I managed to get a screenshot of it

**Comment by ALTaleX531** [comment]
can't reproduce that

**Comment by ALTaleX531** [comment]
Moved to #30.
