### ISSUE TITLE
[Legacy Branch] Blur is sometimes rendered as solid black.

### ISSUE THREAD

**Issue by ALTaleX531** [ALTaleX531/OpenGlass#30]
## Description
Some software that uses DirectX rendering bypasses the DWM, making it impossible for OpenGlass to get their content, and the blur is sometimes rendered as solid black.
eg. VMWare, VLC player, Wallpaper Engine, internet browsers
I can't reproduce it because the VM doesn't allow this optimization behavior for the apps in it.

## Related Issues
1. #13 
2. #20
3. #28 (maybe?)

## Possible Solution
[Disabling Multi-Plane Overlay (MPO) fixed all desktop flickering/stuttering on my 6900XT : r/Amd](https://www.reddit.com/r/Amd/comments/yvyqc7/disabling_multiplane_overlay_mpo_fixed_all/)
I haven't tested it yet, but it might work.

**Comment by Dulappy** [comment]
The solution you included did in fact fix the issue. Thanks!

**Comment by ALTaleX531** [comment]
Fixed.
