### ISSUE TITLE
[Legacy Branch] OpenGlass glitches on right to left Windows

### ISSUE THREAD

**Issue by novatiberium** [ALTaleX531/OpenGlass#32]
[had to repost because I forgot label]

While using OpenGlass on a RTL version of Windows (in my case Hebrew, but the same goes for Arabic, Urdu, and other RTL languages), I notice that the window titles glitch. Also, the reflections are not accurate (pay attention to this screenshot's About Windows dialog), the titlebar feels like a mirror when in fact it should be the same as in LTR Windows).![image](https://github.com/user-attachments/assets/8f79b513-f6e0-4f38-93c0-1056cdf84c5d)

It shows properly if the Windows is LTR though.
![image](https://github.com/user-attachments/assets/3988454d-3c79-46c1-883e-afb38996e269)

**Comment by novatiberium** [comment]
![תמונה](https://github.com/user-attachments/assets/2fdae2d9-a093-4b2d-9563-ed801196218f)
![תמונה](https://github.com/user-attachments/assets/1662e9c2-96c0-41aa-9128-4b19af9529c4)

Close up of the About Windows dialog box. The top image is RTL (Hebrew), if you pay attention you can see that some of the elements is not right. The blur is also mirrored as I mentioned, not consistent with how it normally would be on LTR (bottom).

**Comment by ALTaleX531** [comment]
I think I'll fix it in the next release.

**Comment by novatiberium** [comment]
Thank you for taking note of that. Does anyone know a Windhawk mod we can temporarily use for now?

**Comment by ALTaleX531** [comment]
Fixed.
