### ISSUE TITLE
[dcomp branch] Add support for Windows 11 24H2

### ISSUE THREAD

**Issue by ALTaleX531** [ALTaleX531/OpenGlass#38]

**Comment by teknixstuff** [comment]
Any chance this could happen soon? Since I've got almost everything except for aero working on W11 24H2 in Revert8Plus v4 now, and this is one of the major things preventing full 24H2 support.

**Comment by DanTheGuy720** [comment]
Would be cool to see this get 24H2 support!

**Comment by ALTaleX531** [comment]
I have already added support for 24H2, but I had hoped to release it after refactoring the code to fix the reported bugs. Since you all really need it, I'll just release it now.

**Comment by Skyyblaze** [comment]
Thank you!

**Comment by teknixstuff** [comment]
> I have already added support for 24H2, but I had hoped to release it after refactoring the code to fix the reported bugs. Since you all really need it, I'll just release it now.

Thanks so much!

**Comment by DanTheGuy720** [comment]
Greatly appreciated <3

**Comment by barrettwashere** [comment]
> I have already added support for 24H2, but I had hoped to release it after refactoring the code to fix the reported bugs. Since you all really need it, I'll just release it now.

so is it  fine for windows 24h2 now?
i want to get this,but another app on my computer,aka neo networks chat gpt jarvis tells me other wise,and i found this when checking his sources.
so is this 24h4 supported now?
