### ISSUE TITLE
[legacy] Aero shader broken for non-Sky color

### ISSUE THREAD

**Issue by wily-coyote** [ALTaleX531/OpenGlass#39]
After the v1.2 refactor, the Aero shader produces inaccurate colors. In my case, I am using Twilight color instead of Sky.

Here are the registry values for the Twilight color:
[Twilight.txt](https://github.com/user-attachments/files/17237007/Twilight.txt)

To use:
1. Download `Twilight.txt` and rename to `Twilight.reg`
2. Merge `Twilight.reg`
3. Restart OpenGlass (or update OpenGlass settings)
4. Compare to Win7; notice faded color.

Additionally, this line seems to be causing it:
https://github.com/ALTaleX531/OpenGlass/blob/0cb01a966969527062d346a2b3b04226ac239917/OpenGlass/GlassRenderer.cpp#L233
Changing it to only `Shared::g_color` fixes it. However, I do not know if this is the proper fix, so I opened an issue instead.

Before:
![imagen](https://github.com/user-attachments/assets/282e7ba8-005e-42e0-8a25-16aba70700c9)

After:
![imagen](https://github.com/user-attachments/assets/db76ea91-c056-4952-b0e6-27830ee34ca2)

**Comment by ALTaleX531** [comment]
I guess that's the problem, ternary operator had the opposite result, thanks for reporting it, I'll release a patch to fix it.
