### ISSUE TITLE
Using a Theme Patcher reverts some Aero color settings on every logoff and lock

### ISSUE THREAD

**Issue by Mrk20200** [ALTaleX531/OpenGlass#4]
### Note
This bug is not caused by OpenGlass, but it is _basically_ the only program using these values, and it is very unlikely that Microsoft would fix this, considering that these values can only be set from either the Registry Editor or third-party tools.

### Problem
The `ColorizationColorBalance` and `ColorizationAfterglowBalance` keys (stored in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\DWM`) get reset to their default values (set by explorer.exe) on every lock and logoff (including shutdowns and restarts), changing how the Aero blur looks. (see the screenshots below)

This problem can be recreated on a fresh install of Windows with either SecureUXTheme (making it hook explorer doesn't affect anything) or UltraUXThemePatcher and a custom theme, which isn't good for the people trying to make their setup look like Windows 7.

### Possible Solution/Workaround
Since this program hooks into DWM and not Explorer (the program that reverts these values), I suggest that these values get renamed to a different name that Explorer won't reset. (maybe `AeroColorBalance` and `AeroAfterglowBalance`?)

### System Info
OS: Windows 10 22H2 (Build 19045.4529)
Tested theme: Aero10 v1.0.3-re
Tested theme patchers: SecureUXTheme v2.2.0 and UltraUXThemePatcher v4.4.2
Third-party software: (only a theme patcher is needed to recreate this bug)

### Screenshots
Before Logoff (should stay the same after):
![before](https://github.com/ALTaleX531/OpenGlass/assets/157867907/6308851b-149d-457c-9f0b-82ee75bf065b)
After Logoff (and after logon):
![after](https://github.com/ALTaleX531/OpenGlass/assets/157867907/0261be77-0d89-479d-a4c4-d221e183a6ec)

**Comment by ALTaleX531** [comment]
workaround added
