### ISSUE TITLE
[Legacy] Reflections look broken when opening/closing windows

### ISSUE THREAD

**Issue by ImSwordQueen** [ALTaleX531/OpenGlass#41]
in OpenGlass Legacy 1.2+ the reflections break when closing/opening windows while using the baked in reflection texture and not the aero peek one from msstyles.

Video comparations:

OpenGlass "1.1":
https://github.com/user-attachments/assets/6a18cbbc-d154-4930-a363-d4f12825260e

OpenGlass 1.2+ (Tested on 1.3. Confirmed to be an issue on 1.2 as well);
https://github.com/user-attachments/assets/1b3e19f2-086d-492e-a13c-1367b193d0fa

Windows 7 (As reference):
https://github.com/user-attachments/assets/630e8f8b-b428-4575-8638-4aa763ec1d7b

Images: 

OpenGlass "1.1":
![image](https://github.com/user-attachments/assets/024de190-16ff-40c0-a13a-e2b7ae0952d1)

OpenGlass 1.2+:
![image](https://github.com/user-attachments/assets/fe9e287e-0b88-419a-944d-82a7d3dbf302)

Windows 7 (Reference):
![image](https://github.com/user-attachments/assets/439041f1-646c-4ace-93db-bb2b99319f27)

**Comment by ALTaleX531** [comment]
Since the reflection rendering part is not yet done for offscreen rendering, I'll treat this issue as an feature request.

**Comment by ALTaleX531** [comment]
Done.
