### ISSUE TITLE
Feature Request: DWM/Aero Shine

### ISSUE THREAD

**Issue by TheDolphinSlayer** [ALTaleX531/OpenGlass#42]
wasn't entirely sure what to call it, but the white corners/shine on windows are baked down in Windows 10 vs Windows 7 where they're real time rendered
![win7](https://github.com/user-attachments/assets/6f8ff43f-e9bf-4282-ab86-a761eafbe79c)

I'm sure this has been requested before/everyone is aware, but I just wanted to put in an official request.

But as you can see the baked shine on msstyles causing this stretching issues on windows, vs windows 7 where they are proper. Just to test, I was using the sheetglass program by Aubymori on 10/7 VM

https://github.com/aubymori/GlassWnd/releases/tag/1.0

(incase anybody wanted to experiment

**Comment by ALTaleX531** [comment]
probably won't be implemented.
