### ISSUE TITLE
[OpenGlass Legacy] Random flashes in borders

### ISSUE THREAD

**Issue by ImSwordQueen** [ALTaleX531/OpenGlass#43]
Almost the same issue as #13 but on OpenGlass Legacy 1.4 and the fix in #30 does not fix the issue.

https://github.com/user-attachments/assets/3cd8a61c-5adc-4a56-a947-335121608aa2

**Comment by ALTaleX531** [comment]
This is not the same thing, the flickering is caused by the lack of a complete implementation of the glass safe zones. If you want to fix it at the moment, you have to enable the `EnableFullDirty` option.
