### ISSUE TITLE
[legacy branch] Aero Peek reflections keep stacking over windows

### ISSUE THREAD

**Issue by n1d3v** [ALTaleX531/OpenGlass#46]
Hello. The `Aero Peek` reflections in OpenGlass stack over windows and looks like this:

![og-w10](https://github.com/user-attachments/assets/706f5cd9-8777-4742-9900-4377d407595e)

While in Windows 7 they look like this:

![aero-w7](https://github.com/user-attachments/assets/55be13a9-6c96-462f-9037-3d13d969cfcb)

This has probably been brought up before and already known, just wanted to make an official issue here.

I'm using Windows 10 21H2 with OpenGlass Legacy v1.4.

**Comment by n1d3v** [comment]
Nevermind, was an Aero Peek Fix bug. Fixed it in the source code and now it works fine.

**Comment by n1d3v** [comment]
I reopened this issue as it is not in fact an Aero Peek Fix bug. When I disabled the fix, the same effect happened. I am using explorer7 (which fixes the Peek because 7 had it working fine) so I don't know the cause of this.

**Comment by ALTaleX531** [comment]
because openglass implementation is not 1:1 for windows 7

**Comment by AryaTwirl** [comment]
@ALTaleX531 Hi, anyway I can turn this off instead like in previous build? Thank you

**Comment by ALTaleX531** [comment]
@AryaTwirl just set reflection opacity to 0
