### ISSUE TITLE
[Legacy] Lag when moving still windows in 1.4 pre-release

### ISSUE THREAD

**Issue by funn-hue** [ALTaleX531/OpenGlass#47]
When you try to drag a window that was left in the same position for like 5-10 seconds you can see a noticeable lag, it does not happen if you drag the window after like 2 seconds, only after 5-10

The intensity slider is also way slower than it was in 1.1 while using accent color sync mod on windhawk

**Comment by ALTaleX531** [comment]
> When you try to drag a window that was left in the same position for like 5-10 seconds you can see a noticeable lag, it does not happen if you drag the window after like 2 seconds, only after 5-10

Cannot be reproduced on 19045.4894.
> The intensity slider is also way slower than it was in 1.1 while using accent color sync mod on windhawk

I think it has to do with the implementation of this mod, because the process of color synchronization is asynchronous.

**Comment by funn-hue** [comment]
> > When you try to drag a window that was left in the same position for like 5-10 seconds you can see a noticeable lag, it does not happen if you drag the window after like 2 seconds, only after 5-10
> 
> Cannot be reproduced on 19045.4894.
> 
> > The intensity slider is also way slower than it was in 1.1 while using accent color sync mod on windhawk
> 
> I think it has to do with the implementation of this mod, because the process of color synchronization is asynchronous.

But everything works fine on 1.1, even the slider isn't laggy

**Comment by ALTaleX531** [comment]
I have already said that whether the slider itself is laggy or not depends on the mod implementation itself. So, I need actual proof and contextual information to test everything you say. For example, your system build number is? What other customization software are you using it with? The mod version and openglass version you use when not experiencing this issue? What mod version and openglass version, when used, reproduces the bug consistently? And finally, a video clip describing the bug in detail.

**Comment by funn-hue** [comment]
> I have already said that whether the slider itself is laggy or not depends on the mod implementation itself. So, I need actual proof and contextual information to test everything you say. For example, your system build number is? What other customization software are you using it with? The mod version and openglass version you use when not experiencing this issue? What mod version and openglass version, when used, reproduces the bug consistently? And finally, a video clip describing the bug in detail.

I'll make sure to include all of this tomorrow

**Comment by funn-hue** [comment]
So i just found the cause of this lag and the intensity slider being choppy, it was the glass reflections. I set the ColorizationGlassReflectionIntensity value to 0, and everything works the same as on version legacy 1.1, except that the glass reflection is turned off. With glass reflection enabled moving a still window causes a noticeable lag spike and the gpu usage of DWM goes up to 40%, with glass reflection disabled there is no lag and the usage goes only up to 13%.

**Comment by ALTaleX531** [comment]
OpenGlass has switched to Microsoft's recommended way of rendering an image in newer versions, but this seems to be proving to be a serious performance degradation, and I'll probably improve glass rendering on lower-end machines next.
