### ISSUE TITLE
24H2 failed injection

### ISSUE THREAD

**Issue by TheDolphinSlayer** [ALTaleX531/OpenGlass#49]
I was trying the latest master build, after running the startup.bat, dwm just crashed. Github won't let me upload the full dmp file, so if you need that ill upload to mega. But here is an image of what it says in Visual Studio

![image](https://github.com/user-attachments/assets/8c6fc55a-6212-4b31-992b-e7b6a623da4c)

**Comment by ALTaleX531** [comment]
The version of Windows you're using is NOT 24H2, there's no reason to use v1.3 at all :)
But, anyway, I fixed the problem and updated the release so you can re-download it.
