### ISSUE TITLE
Button Glow Cutoff?

### ISSUE THREAD

**Issue by ivan-the-bio-lover-42** [ALTaleX531/OpenGlass#50]
This is definitely a minor thing but something I noticed regarding the button glow in OpenGlass (currently on 1.3 Legacy)

**Some relevant resources I am using:** 
StartIsBack
Aero10 by vaporvance
**Windhawk mods:**
Inactive Button Opacity
Restore Windows 7 Caption Buttons

When I hover through the titlebar buttons in sequence, the glow from the button under the cursor is cut off by the button that I was hovering over previously. To demonstrate:

https://github.com/user-attachments/assets/0eb5aff4-ec4b-4332-9f22-08c30c1dfa80

This does not happen when the window is inactive, and the glow effect from the buttons is unaffected by the neighboring buttons.

https://github.com/user-attachments/assets/813c5429-3c60-42fb-b7fa-feba5caa1fc2

It's a very small detail but perhaps it could be fixed. I am curious as to what might be causing it. This did not occur in a [test build of DWMBlurGlass with button glow](https://github.com/Maplespe/DWMBlurGlass/discussions/282#discussioncomment-9245189). Thanks in advance for reading!

**Comment by ALTaleX531** [comment]
1. first of all openglass never intended to add button glow, i won't deal with the issue about it, this feature was added by a pr
2. openglass's button glow isn't really responsible for rendering the button glow, it just restores the code that was removed from the dwm that was responsible for loading the glow atlas, in fact it's still the dwm itself that renders the glow, so there's no way to fix that either

**Comment by AlexanderJustin183** [comment]
> This is definitely a minor thing but something I noticed regarding the button glow in OpenGlass (currently on 1.3 Legacy)
> 
> **Some relevant resources I am using:** StartIsBack Aero10 by vaporvance **Windhawk mods:** Inactive Button Opacity Restore Windows 7 Caption Buttons
> 
> When I hover through the titlebar buttons in sequence, the glow from the button under the cursor is cut off by the button that I was hovering over previously. To demonstrate:
> 
>  OpenGlass.ButtonGlow.-.Made.with.Clipchamp.mp4 
> This does not happen when the window is inactive, and the glow effect from the buttons is unaffected by the neighboring buttons.
> 
>  OpenGlass.Button.Glow.Inactive.-.Made.with.Clipchamp.mp4 
> It's a very small detail but perhaps it could be fixed. I am curious as to what might be causing it. This did not occur in a [test build of DWMBlurGlass with button glow](https://github.com/Maplespe/DWMBlurGlass/discussions/282#discussioncomment-9245189). Thanks in advance for reading!

Could you give me a copy of OpenGlass pr version with button glow? code or binaries
