### ISSUE TITLE
"ColorizationBlurBalance" doesn't seem to update

### ISSUE THREAD

**Issue by spawncampingnoob** [ALTaleX531/OpenGlass#6]
https://youtu.be/-5res9mBPwg - video demonstration

so for some reason, this registry value just doesn't update at all for me. not even signing out/in or even restarting seems to get it to work.

i'm on the latest release (1.2), haven't tried any older versions so idk if this is a bug, or if it's just my pc being wack

**Comment by ALTaleX531** [comment]
OpenGlass does not use `ColorizationBlurBalance`, instead it uses `GlassOpacity`.

**Comment by spawncampingnoob** [comment]
my bad, i'm so used to dwmblurglass i didn't think to check whether i'd gotten the name of the value wrong lol
