### ISSUE TITLE
weird flickering

### ISSUE THREAD

**Issue by froggz19** [ALTaleX531/OpenGlass#60]
I don't remember having this issue with DWMBlurGlass, any way to fix it?

https://github.com/user-attachments/assets/21b6ec85-66b7-4bce-9a40-947de4f32295

Registry
![image](https://github.com/user-attachments/assets/e8b4c905-079a-41b4-a25a-9815e26949cb)

**Comment by Undisputed00x** [comment]
Its already discussed here: https://github.com/ALTaleX531/OpenGlass/discussions/59
