### ISSUE TITLE
Consider using MSDIA instead of DbgHelp for symbols

### ISSUE THREAD

**Issue by aubymori** [ALTaleX531/OpenGlass#64]
I've had issues downloading symbols on both OpenGlass and DWMBlurGlass, and have had to copy over symbols from Windhawk many times when installing them. I had no idea what was happening before, but I've just realized that it could be DbgHelp that could be the issue.

This is what happens when I try to download symbols with OpenGlass:
![image](https://github.com/user-attachments/assets/0bc89b6d-b3fb-42f3-b049-05d47b241835)

I've never had this issue with downloading symbols with Windhawk (or its Windhawk Symbol Helper utility), and I believe it may be because Windhawk uses MSDIA and not DbgHelp.

**Comment by DAPOPOBEFASTONYOAZZ** [comment]
Interesting. I have not had any issues downloading any symbol files from either MSDIA or DbgHelp. Can you share more information about your setup perhaps?

**Comment by ALTaleX531** [comment]
I might implement it in v2. After a bit of research, I've found that some users have DWM blocked from using any Internet connection, or the winhttp api doesn't work properly, and all operations return `ERROR_INTERNET_CANNOT_CONNECT`.

**Comment by ALTaleX531** [comment]
MSDIA uses symsrv to download symbols, it only has the ability to parse symbols, I might consider copying some of the PDBDownloader functions into OpenGlass.
