### ISSUE TITLE
User-Friendly AeroGlass settings menu

### ISSUE THREAD

**Issue by Milicent-Heeler** [ALTaleX531/OpenGlass#68]
###(Idea) I would like  a settings menu to tweak how the AeroGlass works.
It would be nice if a user-friendly settings menu for this application to tweak it's settings would be nice. For example, you could add a setting where you can choose if you want a reflection or like Glass8, you can have a setting that allows you to choose whether you want the default windows 11/10 close, maximize and minimize buttons, or you could have the windows 8/8.1/7 close, maximize and minimize buttons. 
This way beginners can use this program in order to get the AeroGlass effect.
Edit: I am still new to github so didn't know there was an Ideas section in Discussions so sorry.

**Comment by ALTaleX531** [comment]
The biggest reason OpenGlass has been designed for advanced users only since its birth is to prevent beginners from screwing up their computers and thus blaming the developers or asking a bunch of basic and stupid questions, you should understand that feature requests like this will never be accepted after I've already replied to the same request as you did before.

If you really want a GUI, you should make a public request to third-party developers to develop a GUI for OpenGlass in the Ideas section in Disscusions.

**Comment by Milicent-Heeler** [comment]
> The biggest reason OpenGlass has been designed for advanced users only since its birth is to prevent beginners from screwing up their computers and thus blaming the developers or asking a bunch of basic and stupid questions, you should understand that feature requests like this will never be accepted after I've already replied to the same request as you did before.
> 
> If you really want a GUI, you should make a public request to third-party developers to develop a GUI for OpenGlass in the Ideas section in Disscusions.

Well, Thanks anyways. Bye!

**Comment by Milicent-Heeler** [comment]
> The biggest reason OpenGlass has been designed for advanced users only since its birth is to prevent beginners from screwing up their computers and thus blaming the developers or asking a bunch of basic and stupid questions, you should understand that feature requests like this will never be accepted after I've already replied to the same request as you did before.
> 
> If you really want a GUI, you should make a public request to third-party developers to develop a GUI for OpenGlass in the Ideas section in Disscusions.

Can I use Glass8's heritage AeroGlassGUI.exe to modify openglass settings?

**Comment by zxrohex** [comment]
> > The biggest reason OpenGlass has been designed for advanced users only since its birth is to prevent beginners from screwing up their computers and thus blaming the developers or asking a bunch of basic and stupid questions, you should understand that feature requests like this will never be accepted after I've already replied to the same request as you did before.
> > If you really want a GUI, you should make a public request to third-party developers to develop a GUI for OpenGlass in the Ideas section in Disscusions.
> 
> Can I use Glass8's heritage AeroGlassGUI.exe to modify openglass settings?

I made/am developing one where I need some testers - I posted it in the discussions. https://github.com/ALTaleX531/OpenGlass/discussions/77
https://github.com/zxrohex/OpenGlassGUI

@ALTaleX531 tagging you because I made one, wanted to ask if you want to help me out with some things?

**Comment by ALTaleX531** [comment]
@zxrohex Im not good at the gui stuff and don't really feel like I can help you much.
