### ISSUE TITLE
Border around programs with aero compatibility

### ISSUE THREAD

**Issue by lucamonfre** [ALTaleX531/OpenGlass#73]
forgive me for not knowing exactly what its called when a program extends the titlebar glass to the search bar (like explorer.exe or internet explorer) but for some reason openglass legacy 1.4 creates a thin border separating the titlebaer from the rest of the window, already fully uninstalled and reinstalled but the issue persists. goes away when i attempt to screenshot it so forgive the phone photo.

![PXL_20241214_151027220](https://github.com/user-attachments/assets/ef291b1f-fdcc-48c1-811e-0dadc560295e)

**Comment by ALTaleX531** [comment]
This looks more like a dwm bug.

**Comment by lucamonfre** [comment]
> This looks more like a dwm bug.

Yeah I got it sorted out. New windows update screwed up some stuff with the resolution so I had to set my resolution in the "list all modes" menu in the display adapter settings. For whatever reason stuff gets weird if u don't use ur default monitor resolution and don't make the adapter "think" it's the new resolution.
