### ISSUE TITLE
[OpenGlass Legacy v1.3/1.4] SIB Taskbar Preview/Jumplist Rendering Issue

### ISSUE THREAD

**Issue by ivan-the-bio-lover-42** [ALTaleX531/OpenGlass#74]
OpenGlass v1.4 looks stunning. I currently have GlassOverrideAccent set to 1, and on SIB I have disabled custom coloring for the taskbar and start menu. This works as intended and I can see the correct color, blur effect, and reflection image on the taskbar and thumbnails as expected. However, these black squares appear on the corners of the previews, and the DWM-drivean blur effect is clearly not transferring to them. They seem to still use the AccentBlur effect and are very dark, as if the coloration had been applied multiple times. The same problem occurs with the jumplists.

![image](https://github.com/user-attachments/assets/02630b2c-c9ed-4de3-b6fb-c4c14eb0cf45)
![image](https://github.com/user-attachments/assets/a477f121-6206-49e5-96d9-ecdffb03d5ab)

I happen to use the SIB 2.9.20++ Tweaker Windhawk mod. I have already tried enabling/disabling the DWM Composition setting on SIB Tweaker to see if that was affecting anything, but no change occurred.

I have also experienced the same issue with OpenGlass Legacy v1.3.

Windows Build: Windows 10 Home Edition 22H2, 19045.5247

**Comment by ALTaleX531** [comment]
It can't be fixed because the blurred areas of startisback are not actually rounded corners.
