### ISSUE TITLE
Text Glow for Windows 11

### ISSUE THREAD

**Issue by Sand216** [ALTaleX531/OpenGlass#75]
Text glow on Windows 11 has been asked for numerous times in the DWMBlurGlass repository, but Maplespe has given no word on if this is something he would do or not. Would it be possible to do this for OpenGlass?

**Comment by ALTaleX531** [comment]
OpenGlass does not plan to implement text glow on Windows 11.

**Comment by Milicent-Heeler** [comment]
> Text glow on Windows 11 has been asked for numerous times in the DWMBlurGlass repository, but Maplespe has given no word on if this is something he would do or not. Would it be possible to do this for OpenGlass?

Your only resort is Windows 7 Themes for windows 11 with OpenGlass or DWMBlurGlass for Text Glow.

**Comment by ALTaleX531** [comment]
@Milicent-Heeler Don't necropost, you have absolutely no idea what we are talking about and everything you say is unrelated to the topic.
