### ISSUE TITLE
"OpenGlass could not download appropriate symbol files"

### ISSUE THREAD

**Issue by IPTVmanreal** [ALTaleX531/OpenGlass#8]
Every time i try to start OpenGlass, it shows the following error, searching for the error code did not help:

![image](https://github.com/ALTaleX531/OpenGlass/assets/99894372/bedecd74-dadd-48c8-92ba-ace2357a4812)

**Comment by ALTaleX531** [comment]
1. Can you successfully access msdl.microsoft.com as the prompt says?
2. Can you make sure that `symsrv.dll` and `dbghelp.dll` are present and complete in the OpenGlass directory?
3. Besides OpenGlass, can other software that requires symbols download the symbols properly?
4. Are you using an insider preview version of Windows?
5. Besides that, what is your system build number and what 3rd party software do you use?

If you're using AWM, and if it works, you can try copying its symbol files to the `symbols` directory in OpenGlass.

**Comment by IPTVmanreal** [comment]
1. I can access msdl.microsoft.com
2. Both files are present
3. I have AWM which was able to retrieve the symbols properly
4. I'm running a standard build of Windows
5. I have Windhawk, AWM and run build 19045.4291

**Comment by IPTVmanreal** [comment]
Do i copy it like this, or do i copy what's inside of the folder

![image](https://github.com/ALTaleX531/OpenGlass/assets/99894372/db2f168d-c81c-4507-8ce3-ceb1b4439b5c)

**Comment by ALTaleX531** [comment]
Please copy inside.

**Comment by IPTVmanreal** [comment]
Now it doesn't do anything, not even a taskbar icon

**Comment by ALTaleX531** [comment]
OpenGlass has found and loaded the symbol file, this seems to be something disrupting it from working properly, can you create and upload a memory dump file for dwm?

**Comment by ALTaleX531** [comment]
Upload it, it indicates a crash in dwm.

**Comment by IPTVmanreal** [comment]
https://files.catbox.moe/dnh3ym.zip

**Comment by ALTaleX531** [comment]
![image](https://github.com/ALTaleX531/OpenGlass/assets/105535231/8ee019ea-a4f8-4c7e-a7c1-a948d4fdedb9)
![image](https://github.com/ALTaleX531/OpenGlass/assets/105535231/efc60b05-33e5-469c-92d8-7262ab8309c5)
This seems to be a crash caused by awm, but I don't know why.

**Comment by ALTaleX531** [comment]
Please try disabling awm and see if OpenGlass still doesn't work properly.

**Comment by IPTVmanreal** [comment]
That worked (ignore the borders, i haven't changed any registry keys yet)

![image](https://github.com/ALTaleX531/OpenGlass/assets/99894372/e934cfc9-cdc7-4738-9fea-cd723bc17f41)
